theme: jekyll-theme-minimal
show_downloads: false
url: "https://chanzuckerberg.github.io"
baseurl: "/cellxgene"

plugins:
  - jekyll-relative-links

logo: cellxgene-logo.png

nav:
  - title: Installation
    url: posts/install
  - title: Gallery
    url: posts/gallery
  - title: Demo datasets
    url: posts/demo-data
  - title: Preparing your data
    url: posts/prepare
  - title: Launching cellxgene
    url: posts/launch
  - title: Hosting cellxgene
    url: posts/hosted
  - title: Annotating data
    url: posts/annotations
  - title: Methods
    url: posts/methods
  - title: Troubleshooting
    url: posts/troubleshooting
  - title: Roadmap
    url: posts/roadmap
  - title: Contributing (ideas or code)
    url: posts/contribute
  - title: Contact & finding help
    url: posts/contact
